services:
  - type: web
    name: planka
    env: docker
    region: oregon
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: planka-db
          property: connectionString
      - key: SECRET_KEY
        value: chave-super-secreta-123
      - key: PORT
        value: 1337
